openapi: 3.2.0
info:
  title: Automation Hub Task Schedules API
  version: v3
  description: Fetch, Upload, Organize, and Distribute Ansible Collections
  contact:
    name: Automation Hub Team
    email: ansible-galaxy-team@redhat.com
    url: https://www.ansible.com/products/automation-hub
  license:
    name: GPLv2+
    url: https://raw.githubusercontent.com/ansible/galaxy_ng/main/LICENSE
  x-logo:
    url: https://pulp.plan.io/attachments/download/517478/pulp_logo_word_rectangle.svg
  x-pulp-app-versions:
    core: 3.49.40
    galaxy: 4.12.0dev
    ansible: 0.25.1
    container: 2.19.5
    certguard: 3.49.40
    file: 3.49.40
  x-pulp-domain-enabled: false
servers:
- url: http://automation-hub-backend-cwa.automation-hub-prod.svc.cluster.local:8000/
tags:
- name: Task Schedules
paths:
  /api/automation-hub/pulp/api/v3/task-schedules/:
    get:
      operationId: task_schedules_list
      description: ViewSet to monitor task schedules.
      summary: List task schedules
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: name
        schema:
          type: string
        description: Filter results where name matches value
      - in: query
        name: name__contains
        schema:
          type: string
        description: Filter results where name contains value
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: ordering
        schema:
          type: array
          items:
            type: string
            enum:
            - -dispatch_interval
            - -name
            - -next_dispatch
            - -pk
            - -pulp_created
            - -pulp_id
            - -pulp_last_updated
            - -task_name
            - dispatch_interval
            - name
            - next_dispatch
            - pk
            - pulp_created
            - pulp_id
            - pulp_last_updated
            - task_name
        description: 'Ordering


          * `pulp_id` - Pulp id

          * `-pulp_id` - Pulp id (descending)

          * `pulp_created` - Pulp created

          * `-pulp_created` - Pulp created (descending)

          * `pulp_last_updated` - Pulp last updated

          * `-pulp_last_updated` - Pulp last updated (descending)

          * `name` - Name

          * `-name` - Name (descending)

          * `next_dispatch` - Next dispatch

          * `-next_dispatch` - Next dispatch (descending)

          * `dispatch_interval` - Dispatch interval

          * `-dispatch_interval` - Dispatch interval (descending)

          * `task_name` - Task name

          * `-task_name` - Task name (descending)

          * `pk` - Pk

          * `-pk` - Pk (descending)'
        explode: false
        style: form
      - in: query
        name: pulp_href__in
        schema:
          type: array
          items:
            type: string
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - in: query
        name: pulp_id__in
        schema:
          type: array
          items:
            type: string
            format: uuid
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - in: query
        name: q
        schema:
          type: string
      - in: query
        name: task_name
        schema:
          type: string
        description: Filter results where task_name matches value
      - in: query
        name: task_name__contains
        schema:
          type: string
        description: Filter results where task_name contains value
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - Task Schedules
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTaskScheduleResponseList'
          description: ''
  /api/automation-hub/pulp/api/v3/task-schedules/{pulp_id}/:
    get:
      operationId: task_schedules_read
      description: ViewSet to monitor task schedules.
      summary: Inspect a task schedule
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this task schedule.
        required: true
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - Task Schedules
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskScheduleResponse'
          description: ''
  /api/automation-hub/pulp/api/v3/task-schedules/{pulp_id}/add_role/:
    post:
      operationId: task_schedules_add_role
      description: Add a role for this object to users/groups.
      summary: Add a role
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this task schedule.
        required: true
      tags:
      - Task Schedules
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NestedRole'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NestedRole'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/NestedRole'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedRoleResponse'
          description: ''
  /api/automation-hub/pulp/api/v3/task-schedules/{pulp_id}/list_roles/:
    get:
      operationId: task_schedules_list_roles
      description: List roles assigned to this object.
      summary: List roles
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this task schedule.
        required: true
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - Task Schedules
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectRolesResponse'
          description: ''
  /api/automation-hub/pulp/api/v3/task-schedules/{pulp_id}/my_permissions/:
    get:
      operationId: task_schedules_my_permissions
      description: List permissions available to the current user on this object.
      summary: List user permissions
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this task schedule.
        required: true
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - Task Schedules
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyPermissionsResponse'
          description: ''
  /api/automation-hub/pulp/api/v3/task-schedules/{pulp_id}/remove_role/:
    post:
      operationId: task_schedules_remove_role
      description: Remove a role for this object from users/groups.
      summary: Remove a role
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this task schedule.
        required: true
      tags:
      - Task Schedules
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NestedRole'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NestedRole'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/NestedRole'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedRoleResponse'
          description: ''
components:
  schemas:
    ObjectRolesResponse:
      type: object
      properties:
        roles:
          type: array
          items:
            $ref: '#/components/schemas/NestedRoleResponse'
      required:
      - roles
    NestedRoleResponse:
      type: object
      description: 'Serializer to add/remove object roles to/from users/groups.


        This is used in conjunction with ``pulpcore.app.viewsets.base.RolesMixin`` and requires the

        underlying object to be passed as ``content_object`` in the context.'
      properties:
        users:
          type: array
          items:
            type: string
            description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
          default: []
        groups:
          type: array
          items:
            type: string
          default: []
        role:
          type: string
      required:
      - role
    PaginatedTaskScheduleResponseList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/TaskScheduleResponse'
    MyPermissionsResponse:
      type: object
      properties:
        permissions:
          type: array
          items:
            type: string
      required:
      - permissions
    NestedRole:
      type: object
      description: 'Serializer to add/remove object roles to/from users/groups.


        This is used in conjunction with ``pulpcore.app.viewsets.base.RolesMixin`` and requires the

        underlying object to be passed as ``content_object`` in the context.'
      properties:
        users:
          type: array
          items:
            type: string
            minLength: 1
            description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
          default: []
        groups:
          type: array
          items:
            type: string
            minLength: 1
          default: []
        role:
          type: string
          minLength: 1
      required:
      - role
    TaskScheduleResponse:
      type: object
      description: 'Base serializer for use with :class:`pulpcore.app.models.Model`


        This ensures that all Serializers provide values for the ''pulp_href` field.


        The class provides a default for the ``ref_name`` attribute in the

        ModelSerializers''s ``Meta`` class. This ensures that the OpenAPI definitions

        of plugins are namespaced properly.'
      properties:
        pulp_href:
          type: string
          format: uri
          readOnly: true
        pulp_created:
          type: string
          format: date-time
          readOnly: true
          description: Timestamp of creation.
        pulp_last_updated:
          type: string
          format: date-time
          readOnly: true
          description: 'Timestamp of the last time this resource was updated. Note: for immutable resources - like content, repository versions, and publication - pulp_created and pulp_last_updated dates will be the same.'
        name:
          type: string
          description: The name of the task schedule.
        task_name:
          type: string
          description: The name of the task to be scheduled.
        dispatch_interval:
          type:
          - string
          - 'null'
          description: Periodicity of the schedule.
        next_dispatch:
          type:
          - string
          - 'null'
          format: date-time
          readOnly: true
          description: Timestamp of the next time the task will be dispatched.
        last_task:
          type: string
          format: uri
          readOnly: true
          description: The last task dispatched by this schedule.
      required:
      - dispatch_interval
      - name
      - task_name
