openapi: 3.2.0
info:
  title: 'Automation Hub Exporters: Pulp API'
  version: v3
  description: Fetch, Upload, Organize, and Distribute Ansible Collections
  contact:
    name: Automation Hub Team
    email: ansible-galaxy-team@redhat.com
    url: https://www.ansible.com/products/automation-hub
  license:
    name: GPLv2+
    url: https://raw.githubusercontent.com/ansible/galaxy_ng/main/LICENSE
  x-logo:
    url: https://pulp.plan.io/attachments/download/517478/pulp_logo_word_rectangle.svg
  x-pulp-app-versions:
    core: 3.49.40
    galaxy: 4.12.0dev
    ansible: 0.25.1
    container: 2.19.5
    certguard: 3.49.40
    file: 3.49.40
  x-pulp-domain-enabled: false
servers:
- url: http://automation-hub-backend-cwa.automation-hub-prod.svc.cluster.local:8000/
tags:
- name: 'Exporters: Pulp'
paths:
  /api/automation-hub/pulp/api/v3/exporters/core/pulp/:
    get:
      operationId: exporters_core_pulp_list
      description: ViewSet for viewing PulpExporters.
      summary: List pulp exporters
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: name
        schema:
          type: string
        description: Filter results where name matches value
      - in: query
        name: name__contains
        schema:
          type: string
        description: Filter results where name contains value
      - in: query
        name: name__icontains
        schema:
          type: string
        description: Filter results where name contains value
      - in: query
        name: name__iexact
        schema:
          type: string
        description: Filter results where name matches value
      - in: query
        name: name__in
        schema:
          type: array
          items:
            type: string
        description: Filter results where name is in a comma-separated list of values
        explode: false
        style: form
      - in: query
        name: name__iregex
        schema:
          type: string
        description: Filter results where name matches regex value
      - in: query
        name: name__istartswith
        schema:
          type: string
        description: Filter results where name starts with value
      - in: query
        name: name__regex
        schema:
          type: string
        description: Filter results where name matches regex value
      - in: query
        name: name__startswith
        schema:
          type: string
        description: Filter results where name starts with value
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: ordering
        schema:
          type: array
          items:
            type: string
            enum:
            - -name
            - -path
            - -pk
            - -pulp_created
            - -pulp_id
            - -pulp_last_updated
            - -pulp_type
            - name
            - path
            - pk
            - pulp_created
            - pulp_id
            - pulp_last_updated
            - pulp_type
        description: 'Ordering


          * `pulp_id` - Pulp id

          * `-pulp_id` - Pulp id (descending)

          * `pulp_created` - Pulp created

          * `-pulp_created` - Pulp created (descending)

          * `pulp_last_updated` - Pulp last updated

          * `-pulp_last_updated` - Pulp last updated (descending)

          * `pulp_type` - Pulp type

          * `-pulp_type` - Pulp type (descending)

          * `name` - Name

          * `-name` - Name (descending)

          * `path` - Path

          * `-path` - Path (descending)

          * `pk` - Pk

          * `-pk` - Pk (descending)'
        explode: false
        style: form
      - in: query
        name: pulp_href__in
        schema:
          type: array
          items:
            type: string
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - in: query
        name: pulp_id__in
        schema:
          type: array
          items:
            type: string
            format: uuid
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - in: query
        name: q
        schema:
          type: string
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Exporters: Pulp'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedPulpExporterResponseList'
          description: ''
    post:
      operationId: exporters_core_pulp_create
      description: ViewSet for viewing PulpExporters.
      summary: Create a pulp exporter
      tags:
      - 'Exporters: Pulp'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PulpExporter'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PulpExporter'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PulpExporter'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PulpExporterResponse'
          description: ''
  /api/automation-hub/pulp/api/v3/exporters/core/pulp/{pulp_id}/:
    get:
      operationId: exporters_core_pulp_read
      description: ViewSet for viewing PulpExporters.
      summary: Inspect a pulp exporter
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this pulp exporter.
        required: true
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Exporters: Pulp'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PulpExporterResponse'
          description: ''
    put:
      operationId: exporters_core_pulp_update
      description: Trigger an asynchronous update task
      summary: Update a pulp exporter
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this pulp exporter.
        required: true
      tags:
      - 'Exporters: Pulp'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PulpExporter'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PulpExporter'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PulpExporter'
        required: true
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ''
    patch:
      operationId: exporters_core_pulp_partial_update
      description: Trigger an asynchronous partial update task
      summary: Update a pulp exporter
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this pulp exporter.
        required: true
      tags:
      - 'Exporters: Pulp'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPulpExporter'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPulpExporter'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPulpExporter'
        required: true
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ''
    delete:
      operationId: exporters_core_pulp_delete
      description: Trigger an asynchronous delete task
      summary: Delete a pulp exporter
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this pulp exporter.
        required: true
      tags:
      - 'Exporters: Pulp'
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ''
components:
  schemas:
    PaginatedPulpExporterResponseList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/PulpExporterResponse'
    AsyncOperationResponse:
      type: object
      description: Serializer for asynchronous operations.
      properties:
        task:
          type: string
          format: uri
          description: The href of the task.
      required:
      - task
    PulpExporterResponse:
      type: object
      description: Serializer for pulp exporters.
      properties:
        pulp_href:
          type: string
          format: uri
          readOnly: true
        pulp_created:
          type: string
          format: date-time
          readOnly: true
          description: Timestamp of creation.
        pulp_last_updated:
          type: string
          format: date-time
          readOnly: true
          description: 'Timestamp of the last time this resource was updated. Note: for immutable resources - like content, repository versions, and publication - pulp_created and pulp_last_updated dates will be the same.'
        name:
          type: string
          description: Unique name of the file system exporter.
        path:
          type: string
          description: File system directory to store exported tar.gzs.
        repositories:
          type: array
          items:
            type: string
            format: uri
        last_export:
          type:
          - string
          - 'null'
          format: uri
          description: Last attempted export for this PulpExporter
      required:
      - name
      - path
      - repositories
    PulpExporter:
      type: object
      description: Serializer for pulp exporters.
      properties:
        name:
          type: string
          minLength: 1
          description: Unique name of the file system exporter.
        path:
          type: string
          minLength: 1
          description: File system directory to store exported tar.gzs.
        repositories:
          type: array
          items:
            type: string
            format: uri
        last_export:
          type:
          - string
          - 'null'
          format: uri
          description: Last attempted export for this PulpExporter
      required:
      - name
      - path
      - repositories
    PatchedPulpExporter:
      type: object
      description: Serializer for pulp exporters.
      properties:
        name:
          type: string
          minLength: 1
          description: Unique name of the file system exporter.
        path:
          type: string
          minLength: 1
          description: File system directory to store exported tar.gzs.
        repositories:
          type: array
          items:
            type: string
            format: uri
        last_export:
          type:
          - string
          - 'null'
          format: uri
          description: Last attempted export for this PulpExporter
