openapi: 3.2.0
info:
  title: Ansible AI Connect. Health API
  version: 1.0.0 (v1)
  description: Equip the automation developer at Lightspeed.
servers:
- url: https://lightspeed-instance/api/v1
  description: Direct access to a Lightspeed instance
- url: https://aap/api/lightspeed/v1
  description: Access through an Ansible Automation Platfrom gateway
tags:
- name: Health
paths:
  /health/:
    get:
      operationId: health_retrieve
      description: Service Liveness Probe View
      summary: Liveness probe
      tags:
      - Health
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: OK
      x-ai-description: Retrieve health status
  /health/status/:
    get:
      operationId: health_status_retrieve
      description: Service Health Check
      summary: Health check with backend server status
      tags:
      - Health
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
              examples:
                ExampleOutput:
                  value:
                    status: ok
                    timestamp: '2023-03-13T17:25:17.240683'
                    version: latest 0.1.202303131417
                    git_commit: b987bc43b90f8aca2deaf3bda85596f4b95a10a0
                    deployed_region: dev
                    dependencies:
                    - name: db
                      status: ok
                      time_taken: 233.538
                    - name: model-server
                      status: ok
                      time_taken: 0.001
                  summary: Example output
          description: ''
        '500':
          description: One or more backend services are unavailable.
      x-ai-description: Retrieve health status with backend servers status
  /health/status/chatbot/:
    get:
      operationId: health_status_chatbot_retrieve
      summary: Chatbot health check
      tags:
      - Health
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: OK
      x-ai-description: Retrieve chatbot health status
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /o/authorize/
          tokenUrl: /o/token/
          scopes:
            read: Read basic user information
            write: Request Ansible content suggestions
            delete: Delete resources
