openapi: 3.2.0
info:
  title: 'Automation Hub Api: Content V3 Collections Versions Copy API'
  version: v3
  description: Fetch, Upload, Organize, and Distribute Ansible Collections
  contact:
    name: Automation Hub Team
    email: ansible-galaxy-team@redhat.com
    url: https://www.ansible.com/products/automation-hub
  license:
    name: GPLv2+
    url: https://raw.githubusercontent.com/ansible/galaxy_ng/main/LICENSE
  x-logo:
    url: https://pulp.plan.io/attachments/download/517478/pulp_logo_word_rectangle.svg
  x-pulp-app-versions:
    core: 3.49.40
    galaxy: 4.12.0dev
    ansible: 0.25.1
    container: 2.19.5
    certguard: 3.49.40
    file: 3.49.40
  x-pulp-domain-enabled: false
servers:
- url: http://automation-hub-backend-cwa.automation-hub-prod.svc.cluster.local:8000/
tags:
- name: 'Api: Content V3 Collections Versions Copy'
paths:
  /api/automation-hub/content/{path}/v3/collections/{namespace}/{name}/versions/{version}/copy/{source_path}/{dest_path}/:
    post:
      operationId: api_automation_hub_content_v3_collections_versions_copy_copy_content
      description: Copy collection version from one repository to another.
      parameters:
      - in: path
        name: dest_path
        schema:
          type: string
        required: true
      - in: path
        name: name
        schema:
          type: string
        required: true
      - in: path
        name: namespace
        schema:
          type: string
        required: true
      - in: path
        name: path
        schema:
          type: string
        required: true
      - in: path
        name: source_path
        schema:
          type: string
        required: true
      - in: path
        name: version
        schema:
          type: string
        required: true
      tags:
      - 'Api: Content V3 Collections Versions Copy'
      responses:
        '200':
          description: No response body
      summary: Api automation hub content v3 collections versions copy copy content
      x-summary-source: derived
