openapi: 3.2.0
info:
  title: Event Driven Ansible Eda Credentials API
  version: 0.2.0
servers:
- url: /api/eda/v1
tags:
- name: eda-credentials
paths:
  /eda-credentials/:
    get:
      operationId: eda_credentials_list
      description: List all EDA credentials
      parameters:
      - in: query
        name: credential_type__kind
        schema:
          type: string
        description: Kind of CredentialType
      - in: query
        name: credential_type__kind__in
        schema:
          type: string
        description: Filter by Credential Type kind (comma-separated).
      - in: query
        name: credential_type__namespace__in
        schema:
          type: string
        description: Filter by Credential Type namespace (comma-separated).
      - in: query
        name: credential_type__namespace__not_in
        schema:
          type: string
        description: Exclude Credential Type namespaces (comma-separated).
      - in: query
        name: credential_type_id
        schema:
          type: number
        description: Filter by Credential Type ID.
      - in: query
        name: name
        schema:
          type: string
        description: Filter by EDA credential name.
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - eda-credentials
      security:
      - EDAJWTAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedEdaCredentialList'
          description: Return a list of EDA credentials.
      summary: Eda credentials list
      x-summary-source: derived
    post:
      operationId: eda_credentials_create
      description: Create a new EDA credential.
      tags:
      - eda-credentials
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EdaCredentialCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EdaCredentialCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EdaCredentialCreate'
        required: true
      security:
      - EDAJWTAuthentication: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdaCredential'
          description: Return the new EDA credential.
      summary: Eda credentials create
      x-summary-source: derived
  /eda-credentials/{id}/input_sources/:
    get:
      operationId: eda_credentials_input_sources_list
      description: List all input_sources for the Credential
      parameters:
      - in: query
        name: credential_type__kind
        schema:
          type: string
        description: Filter by Credential Type kind.
      - in: query
        name: credential_type__kind__in
        schema:
          type: string
        description: Filter by Credential Type kind (comma-separated).
      - in: query
        name: credential_type__namespace__in
        schema:
          type: string
        description: Filter by Credential Type namespace (comma-separated).
      - in: query
        name: credential_type__namespace__not_in
        schema:
          type: string
        description: Exclude Credential Type namespaces (comma-separated).
      - in: query
        name: credential_type_id
        schema:
          type: number
        description: Filter by Credential Type ID.
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this credential.
        required: true
      - in: query
        name: name
        schema:
          type: string
        description: Filter by EDA credential name.
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - eda-credentials
      security:
      - EDAJWTAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCredentialInputSourceList'
          description: ''
      summary: Eda credentials input sources list
      x-summary-source: derived
  /eda-credentials/{id}/:
    get:
      operationId: eda_credentials_retrieve
      description: Get EDA credential by id
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this eda credential.
        required: true
      - in: query
        name: refs
        schema:
          type: string
          enum:
          - 'false'
          - 'true'
        description: Query resources that have reference to the credential by its id
      tags:
      - eda-credentials
      security:
      - EDAJWTAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdaCredential'
          description: Return an EDA credential by id.
      summary: Eda credentials retrieve
      x-summary-source: derived
    patch:
      operationId: eda_credentials_partial_update
      description: Partial update of an EDA credential
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this eda credential.
        required: true
      tags:
      - eda-credentials
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedEdaCredentialUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedEdaCredentialUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedEdaCredentialUpdate'
      security:
      - EDAJWTAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdaCredential'
          description: Update successful. Return an updated EDA credential.
      summary: Eda credentials partial update
      x-summary-source: derived
    delete:
      operationId: eda_credentials_destroy
      description: Delete an eda credential by id
      parameters:
      - in: query
        name: force
        schema:
          type: boolean
        description: Force deletion if there are dependent objects
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this eda credential.
        required: true
      tags:
      - eda-credentials
      security:
      - EDAJWTAuthentication: []
      responses:
        '204':
          description: Delete successful.
      summary: Eda credentials destroy
      x-summary-source: derived
  /eda-credentials/{id}/copy/:
    post:
      operationId: eda_credentials_copy_create
      description: Copy an EDA credential.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this eda credential.
        required: true
      tags:
      - eda-credentials
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EdaCredentialCopy'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EdaCredentialCopy'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EdaCredentialCopy'
        required: true
      security:
      - EDAJWTAuthentication: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdaCredential'
          description: Return the copied EDA credential.
        '404':
          description: EDA credential not found.
      summary: Eda credentials copy create
      x-summary-source: derived
  /eda-credentials/{id}/test/:
    post:
      operationId: eda_credentials_test_create
      description: Test an external EDA credential.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this eda credential.
        required: true
      tags:
      - eda-credentials
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EdaCredentialTest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EdaCredentialTest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EdaCredentialTest'
      security:
      - EDAJWTAuthentication: []
      responses:
        '202':
          description: Test was successful.
        '400':
          description: Test failed.
      summary: Eda credentials test create
      x-summary-source: derived
components:
  schemas:
    PaginatedEdaCredentialList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: /eda/api/v1/example/?page=51&page_size=100
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: /eda/api/v1/example/?page=49&page_size=100
        page_size:
          type:
          - integer
          - 'null'
          example: 100
        page:
          type:
          - integer
          - 'null'
          example: 50
        results:
          type: array
          items:
            $ref: '#/components/schemas/EdaCredential'
    EdaCredential:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        inputs:
          type: object
          additionalProperties: true
          readOnly: true
        credential_type:
          allOf:
          - $ref: '#/components/schemas/CredentialTypeRef'
        references:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/EdaCredentialReference'
        created_by:
          type: object
          properties:
            id:
              type: integer
            username:
              type: string
            first_name:
              type: string
            last_name:
              type: string
        modified_by:
          type: object
          properties:
            id:
              type: integer
            username:
              type: string
            first_name:
              type: string
            last_name:
              type: string
        id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        modified_at:
          type: string
          format: date-time
          readOnly: true
        managed:
          type: boolean
          readOnly: true
        organization:
          $ref: '#/components/schemas/OrganizationRef'
      required:
      - created_at
      - created_by
      - id
      - inputs
      - managed
      - modified_at
      - modified_by
      - name
      - organization
    PaginatedCredentialInputSourceList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: /eda/api/v1/example/?page=51&page_size=100
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: /eda/api/v1/example/?page=49&page_size=100
        page_size:
          type:
          - integer
          - 'null'
          example: 100
        page:
          type:
          - integer
          - 'null'
          example: 50
        results:
          type: array
          items:
            $ref: '#/components/schemas/CredentialInputSource'
    EdaCredentialReference:
      type: object
      properties:
        type:
          type: string
          description: Type of the related resource
        id:
          type: integer
          description: ID of the related resource
        name:
          type: string
          description: Name of the related resource
        uri:
          type: string
          format: uri
          description: URI of the related resource
      required:
      - id
      - name
      - type
      - uri
    CredentialInputSource:
      type: object
      description: Serializer used during a GET.
      properties:
        description:
          type: string
        metadata:
          type: string
        references:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/EdaCredentialReference'
        created_by:
          type: object
          properties:
            id:
              type: integer
            username:
              type: string
            first_name:
              type: string
            last_name:
              type: string
        modified_by:
          type: object
          properties:
            id:
              type: integer
            username:
              type: string
            first_name:
              type: string
            last_name:
              type: string
        input_field_name:
          type: string
          maxLength: 1024
        source_credential:
          type:
          - integer
          - 'null'
          description: External credential
        target_credential:
          type:
          - integer
          - 'null'
          description: Non external credential
        id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        modified_at:
          type: string
          format: date-time
          readOnly: true
        organization:
          $ref: '#/components/schemas/OrganizationRef'
      required:
      - created_at
      - created_by
      - id
      - input_field_name
      - modified_at
      - modified_by
      - organization
      - target_credential
    EdaCredentialCreate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        inputs: {}
        credential_type_id:
          type: integer
        organization_id:
          type: integer
      required:
      - credential_type_id
      - inputs
      - name
      - organization_id
    CredentialTypeRef:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        namespace:
          type:
          - string
          - 'null'
        kind:
          type: string
      required:
      - id
      - name
    EdaCredentialCopy:
      type: object
      properties:
        name:
          type: string
          description: Name of the new credintial
      required:
      - name
    PatchedEdaCredentialUpdate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        inputs: {}
        organization_id:
          type: integer
    OrganizationRef:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          description: The name of this resource.
          maxLength: 512
        description:
          type: string
          description: The organization description.
      required:
      - id
      - name
    EdaCredentialTest:
      type: object
      description: Serializer for the Credential Test.
      properties:
        metadata:
          description: Metadata of the credential for testing
  securitySchemes:
    EDAJWTAuthentication:
      type: apiKey
      name: X-DAB-JW-TOKEN
      in: header
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
