openapi: 3.2.0
info:
  title: 'Automation Hub Api: _Ui V1 Users API'
  version: v3
  description: Fetch, Upload, Organize, and Distribute Ansible Collections
  contact:
    name: Automation Hub Team
    email: ansible-galaxy-team@redhat.com
    url: https://www.ansible.com/products/automation-hub
  license:
    name: GPLv2+
    url: https://raw.githubusercontent.com/ansible/galaxy_ng/main/LICENSE
  x-logo:
    url: https://pulp.plan.io/attachments/download/517478/pulp_logo_word_rectangle.svg
  x-pulp-app-versions:
    core: 3.49.40
    galaxy: 4.12.0dev
    ansible: 0.25.1
    container: 2.19.5
    certguard: 3.49.40
    file: 3.49.40
  x-pulp-domain-enabled: false
servers:
- url: http://automation-hub-backend-cwa.automation-hub-prod.svc.cluster.local:8000/
tags:
- name: 'Api: _Ui V1 Users'
paths:
  /api/automation-hub/_ui/v1/users/:
    get:
      operationId: api_automation_hub__ui_v1_users_list
      summary: List users
      parameters:
      - in: query
        name: date_joined
        schema:
          type: string
          format: date-time
      - in: query
        name: email
        schema:
          type: string
      - in: query
        name: email__contains
        schema:
          type: string
      - in: query
        name: email__startswith
        schema:
          type: string
      - in: query
        name: first_name
        schema:
          type: string
      - in: query
        name: first_name__contains
        schema:
          type: string
      - in: query
        name: first_name__startswith
        schema:
          type: string
      - in: query
        name: groups
        schema:
          type: array
          items:
            type: integer
            format: int64
        explode: true
        style: form
      - in: query
        name: groups__name
        schema:
          type: string
      - in: query
        name: last_name
        schema:
          type: string
      - in: query
        name: last_name__contains
        schema:
          type: string
      - in: query
        name: last_name__startswith
        schema:
          type: string
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: sort
        schema:
          type: array
          items:
            type: string
            enum:
            - -date_joined
            - -email
            - -first_name
            - -last_name
            - -username
            - date_joined
            - email
            - first_name
            - last_name
            - username
        description: 'Ordering


          * `username` - Username

          * `-username` - Username (descending)

          * `email` - Email

          * `-email` - Email (descending)

          * `first_name` - First name

          * `-first_name` - First name (descending)

          * `last_name` - Last name

          * `-last_name` - Last name (descending)

          * `date_joined` - Date joined

          * `-date_joined` - Date joined (descending)'
        explode: false
        style: form
      - in: query
        name: username
        schema:
          type: string
      - in: query
        name: username__contains
        schema:
          type: string
      - in: query
        name: username__startswith
        schema:
          type: string
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Api: _Ui V1 Users'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserResponseList'
          description: ''
    post:
      operationId: api_automation_hub__ui_v1_users_create
      summary: Create an user
      tags:
      - 'Api: _Ui V1 Users'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: ''
  /api/automation-hub/_ui/v1/users/{id}/:
    get:
      operationId: api_automation_hub__ui_v1_users_read
      summary: Inspect an user
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        description: A unique integer value identifying this user.
        required: true
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Api: _Ui V1 Users'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: ''
    put:
      operationId: api_automation_hub__ui_v1_users_update
      summary: Update an user
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        description: A unique integer value identifying this user.
        required: true
      tags:
      - 'Api: _Ui V1 Users'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: ''
    patch:
      operationId: api_automation_hub__ui_v1_users_partial_update
      summary: Update an user
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        description: A unique integer value identifying this user.
        required: true
      tags:
      - 'Api: _Ui V1 Users'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUser'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: ''
    delete:
      operationId: api_automation_hub__ui_v1_users_delete
      summary: Delete an user
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        description: A unique integer value identifying this user.
        required: true
      tags:
      - 'Api: _Ui V1 Users'
      responses:
        '204':
          description: No response body
components:
  schemas:
    PatchedUser:
      type: object
      properties:
        username:
          type: string
          minLength: 1
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        groups:
          type: array
          items:
            type: integer
            format: int64
          description: The groups this user belongs to. A user will get all permissions granted to each of their groups.
        password:
          type: string
          writeOnly: true
          maxLength: 128
        is_superuser:
          type: boolean
          title: Superuser status
          description: Designates that this user has all permissions without explicitly assigning them.
    User:
      type: object
      properties:
        username:
          type: string
          minLength: 1
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        groups:
          type: array
          items:
            type: integer
            format: int64
          description: The groups this user belongs to. A user will get all permissions granted to each of their groups.
        password:
          type: string
          writeOnly: true
          maxLength: 128
        is_superuser:
          type: boolean
          title: Superuser status
          description: Designates that this user has all permissions without explicitly assigning them.
      required:
      - username
    PaginatedUserResponseList:
      type: object
      properties:
        meta:
          type: object
          properties:
            count:
              type: integer
              example: 123
        links:
          type: object
          properties:
            first:
              type:
              - string
              - 'null'
            previous:
              type:
              - string
              - 'null'
            next:
              type:
              - string
              - 'null'
            last:
              type:
              - string
              - 'null'
        data:
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'
    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        groups:
          type: array
          items:
            type: integer
            format: int64
          description: The groups this user belongs to. A user will get all permissions granted to each of their groups.
        date_joined:
          type: string
          format: date-time
          readOnly: true
        is_superuser:
          type: boolean
          title: Superuser status
          description: Designates that this user has all permissions without explicitly assigning them.
        auth_provider:
          type: string
          readOnly: true
      required:
      - username
