openapi: 3.2.0
info:
  title: 'Automation Hub Api: _Ui V2 Organizations API'
  version: v3
  description: Fetch, Upload, Organize, and Distribute Ansible Collections
  contact:
    name: Automation Hub Team
    email: ansible-galaxy-team@redhat.com
    url: https://www.ansible.com/products/automation-hub
  license:
    name: GPLv2+
    url: https://raw.githubusercontent.com/ansible/galaxy_ng/main/LICENSE
  x-logo:
    url: https://pulp.plan.io/attachments/download/517478/pulp_logo_word_rectangle.svg
  x-pulp-app-versions:
    core: 3.49.40
    galaxy: 4.12.0dev
    ansible: 0.25.1
    container: 2.19.5
    certguard: 3.49.40
    file: 3.49.40
  x-pulp-domain-enabled: false
servers:
- url: http://automation-hub-backend-cwa.automation-hub-prod.svc.cluster.local:8000/
tags:
- name: 'Api: _Ui V2 Organizations'
paths:
  /api/automation-hub/_ui/v2/organizations/:
    get:
      operationId: api_automation_hub__ui_v2_organizations_list
      summary: List organizations
      parameters:
      - in: query
        name: name
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: resource__ansible_id
        schema:
          type: string
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Api: _Ui V2 Organizations'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedOrganizationResponseList'
          description: ''
    post:
      operationId: api_automation_hub__ui_v2_organizations_create
      summary: Create an organization
      tags:
      - 'Api: _Ui V2 Organizations'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Organization'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Organization'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationResponse'
          description: ''
  /api/automation-hub/_ui/v2/organizations/{id}/:
    get:
      operationId: api_automation_hub__ui_v2_organizations_read
      summary: Inspect an organization
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        description: A unique integer value identifying this organization.
        required: true
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Api: _Ui V2 Organizations'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationResponse'
          description: ''
    put:
      operationId: api_automation_hub__ui_v2_organizations_update
      summary: Update an organization
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        description: A unique integer value identifying this organization.
        required: true
      tags:
      - 'Api: _Ui V2 Organizations'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Organization'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Organization'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationResponse'
          description: ''
    patch:
      operationId: api_automation_hub__ui_v2_organizations_partial_update
      summary: Update an organization
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        description: A unique integer value identifying this organization.
        required: true
      tags:
      - 'Api: _Ui V2 Organizations'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedOrganization'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedOrganization'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedOrganization'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationResponse'
          description: ''
    delete:
      operationId: api_automation_hub__ui_v2_organizations_delete
      summary: Delete an organization
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        description: A unique integer value identifying this organization.
        required: true
      tags:
      - 'Api: _Ui V2 Organizations'
      responses:
        '204':
          description: No response body
components:
  schemas:
    OrganizationResponse:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
          description: The name of this resource.
          maxLength: 512
        resource:
          type: string
          readOnly: true
      required:
      - name
    PaginatedOrganizationResponseList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationResponse'
    PatchedOrganization:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          description: The name of this resource.
          maxLength: 512
    Organization:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          description: The name of this resource.
          maxLength: 512
      required:
      - name
