openapi: 3.2.0
info:
  title: 'Automation Hub Api: V3 Openapi.Json API'
  version: v3
  description: Fetch, Upload, Organize, and Distribute Ansible Collections
  contact:
    name: Automation Hub Team
    email: ansible-galaxy-team@redhat.com
    url: https://www.ansible.com/products/automation-hub
  license:
    name: GPLv2+
    url: https://raw.githubusercontent.com/ansible/galaxy_ng/main/LICENSE
  x-logo:
    url: https://pulp.plan.io/attachments/download/517478/pulp_logo_word_rectangle.svg
  x-pulp-app-versions:
    core: 3.49.40
    galaxy: 4.12.0dev
    ansible: 0.25.1
    container: 2.19.5
    certguard: 3.49.40
    file: 3.49.40
  x-pulp-domain-enabled: false
servers:
- url: http://automation-hub-backend-cwa.automation-hub-prod.svc.cluster.local:8000/
tags:
- name: 'Api: V3 Openapi.Json'
paths:
  /api/automation-hub/v3/openapi.json:
    get:
      operationId: api_automation_hub_v3_openapi.json_get
      description: 'Control authentication with GALAXY_API_SPEC_REQUIRE_AUTHENTICATION

        apply to galaxy_ng openapi endpoints and monkey-patch pulp openapi endpoints.'
      parameters:
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - en-us
          - es
          - fr
          - ja
          - ko
          - nl
          - zh-hans
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Api: V3 Openapi.Json'
      security:
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
          description: ''
      summary: Api automation hub v3 openapi json get
      x-summary-source: derived
