openapi: 3.2.0
info:
  title: 'Automation Hub Api: _Ui V1 Me API'
  version: v3
  description: Fetch, Upload, Organize, and Distribute Ansible Collections
  contact:
    name: Automation Hub Team
    email: ansible-galaxy-team@redhat.com
    url: https://www.ansible.com/products/automation-hub
  license:
    name: GPLv2+
    url: https://raw.githubusercontent.com/ansible/galaxy_ng/main/LICENSE
  x-logo:
    url: https://pulp.plan.io/attachments/download/517478/pulp_logo_word_rectangle.svg
  x-pulp-app-versions:
    core: 3.49.40
    galaxy: 4.12.0dev
    ansible: 0.25.1
    container: 2.19.5
    certguard: 3.49.40
    file: 3.49.40
  x-pulp-domain-enabled: false
servers:
- url: http://automation-hub-backend-cwa.automation-hub-prod.svc.cluster.local:8000/
tags:
- name: 'Api: _Ui V1 Me'
paths:
  /api/automation-hub/_ui/v1/me/:
    get:
      operationId: api_automation_hub__ui_v1_me_read
      tags:
      - 'Api: _Ui V1 Me'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentUserResponse'
          description: ''
      summary: Api automation hub ui v1 me read
      x-summary-source: derived
    put:
      operationId: api_automation_hub__ui_v1_me_update
      tags:
      - 'Api: _Ui V1 Me'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CurrentUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CurrentUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CurrentUser'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentUserResponse'
          description: ''
      summary: Api automation hub ui v1 me update
      x-summary-source: derived
components:
  schemas:
    CurrentUser:
      type: object
      properties:
        username:
          type: string
          minLength: 1
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        password:
          type: string
          writeOnly: true
          maxLength: 128
        is_superuser:
          type: boolean
          title: Superuser status
          description: Designates that this user has all permissions without explicitly assigning them.
      required:
      - username
    CurrentUserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        groups:
          type: array
          items:
            type: integer
            format: int64
          readOnly: true
          description: The groups this user belongs to. A user will get all permissions granted to each of their groups.
        date_joined:
          type: string
          format: date-time
          readOnly: true
        is_superuser:
          type: boolean
          title: Superuser status
          description: Designates that this user has all permissions without explicitly assigning them.
        auth_provider:
          type: string
          readOnly: true
        model_permissions:
          type: object
          readOnly: true
        is_anonymous:
          type: string
          readOnly: true
      required:
      - username
