openapi: 3.2.0
info:
  title: 'Automation Hub Pulp_Ansible: Default Api V3 Collections…'
  version: v3
  description: Fetch, Upload, Organize, and Distribute Ansible Collections
  contact:
    name: Automation Hub Team
    email: ansible-galaxy-team@redhat.com
    url: https://www.ansible.com/products/automation-hub
  license:
    name: GPLv2+
    url: https://raw.githubusercontent.com/ansible/galaxy_ng/main/LICENSE
  x-logo:
    url: https://pulp.plan.io/attachments/download/517478/pulp_logo_word_rectangle.svg
  x-pulp-app-versions:
    core: 3.49.40
    galaxy: 4.12.0dev
    ansible: 0.25.1
    container: 2.19.5
    certguard: 3.49.40
    file: 3.49.40
  x-pulp-domain-enabled: false
servers:
- url: http://automation-hub-backend-cwa.automation-hub-prod.svc.cluster.local:8000/
tags:
- name: 'Pulp_Ansible: Default Api V3 Collections Versions'
paths:
  /pulp_ansible/galaxy/default/api/v3/collections/{namespace}/{name}/versions/:
    get:
      operationId: pulp_ansible_galaxy_default_api_v3_collections_versions_list
      description: Legacy v3 endpoint.
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: path
        name: name
        schema:
          type: string
        required: true
      - in: query
        name: name
        schema:
          type: string
      - in: path
        name: namespace
        schema:
          type: string
        required: true
      - in: query
        name: namespace
        schema:
          type: string
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: ordering
        schema:
          type: array
          items:
            type: string
            enum:
            - -authors
            - -contents
            - -dependencies
            - -description
            - -docs_blob
            - -documentation
            - -files
            - -homepage
            - -is_highest
            - -issues
            - -license
            - -manifest
            - -name
            - -namespace
            - -pk
            - -pulp_created
            - -pulp_id
            - -pulp_last_updated
            - -pulp_type
            - -repository
            - -requires_ansible
            - -search_vector
            - -sha256
            - -timestamp_of_interest
            - -upstream_id
            - -version
            - -version_major
            - -version_minor
            - -version_patch
            - -version_prerelease
            - authors
            - contents
            - dependencies
            - description
            - docs_blob
            - documentation
            - files
            - homepage
            - is_highest
            - issues
            - license
            - manifest
            - name
            - namespace
            - pk
            - pulp_created
            - pulp_id
            - pulp_last_updated
            - pulp_type
            - repository
            - requires_ansible
            - search_vector
            - sha256
            - timestamp_of_interest
            - upstream_id
            - version
            - version_major
            - version_minor
            - version_patch
            - version_prerelease
        description: 'Ordering


          * `pulp_id` - Pulp id

          * `-pulp_id` - Pulp id (descending)

          * `pulp_created` - Pulp created

          * `-pulp_created` - Pulp created (descending)

          * `pulp_last_updated` - Pulp last updated

          * `-pulp_last_updated` - Pulp last updated (descending)

          * `pulp_type` - Pulp type

          * `-pulp_type` - Pulp type (descending)

          * `upstream_id` - Upstream id

          * `-upstream_id` - Upstream id (descending)

          * `timestamp_of_interest` - Timestamp of interest

          * `-timestamp_of_interest` - Timestamp of interest (descending)

          * `authors` - Authors

          * `-authors` - Authors (descending)

          * `contents` - Contents

          * `-contents` - Contents (descending)

          * `dependencies` - Dependencies

          * `-dependencies` - Dependencies (descending)

          * `description` - Description

          * `-description` - Description (descending)

          * `docs_blob` - Docs blob

          * `-docs_blob` - Docs blob (descending)

          * `manifest` - Manifest

          * `-manifest` - Manifest (descending)

          * `files` - Files

          * `-files` - Files (descending)

          * `documentation` - Documentation

          * `-documentation` - Documentation (descending)

          * `homepage` - Homepage

          * `-homepage` - Homepage (descending)

          * `issues` - Issues

          * `-issues` - Issues (descending)

          * `license` - License

          * `-license` - License (descending)

          * `name` - Name

          * `-name` - Name (descending)

          * `namespace` - Namespace

          * `-namespace` - Namespace (descending)

          * `repository` - Repository

          * `-repository` - Repository (descending)

          * `requires_ansible` - Requires ansible

          * `-requires_ansible` - Requires ansible (descending)

          * `sha256` - Sha256

          * `-sha256` - Sha256 (descending)

          * `version` - Version

          * `-version` - Version (descending)

          * `version_major` - Version major

          * `-version_major` - Version major (descending)

          * `version_minor` - Version minor

          * `-version_minor` - Version minor (descending)

          * `version_patch` - Version patch

          * `-version_patch` - Version patch (descending)

          * `version_prerelease` - Version prerelease

          * `-version_prerelease` - Version prerelease (descending)

          * `is_highest` - Is highest

          * `-is_highest` - Is highest (descending)

          * `search_vector` - Search vector

          * `-search_vector` - Search vector (descending)

          * `pk` - Pk

          * `-pk` - Pk (descending)'
        explode: false
        style: form
      - in: query
        name: orphaned_for
        schema:
          type: number
        description: Minutes Content has been orphaned for. -1 uses ORPHAN_PROTECTION_TIME.
      - in: query
        name: pulp_href__in
        schema:
          type: array
          items:
            type: string
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - in: query
        name: pulp_id__in
        schema:
          type: array
          items:
            type: string
            format: uuid
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - in: query
        name: q
        schema:
          type: string
      - in: query
        name: repository_version
        schema:
          type: string
        description: Repository Version referenced by HREF
      - in: query
        name: repository_version_added
        schema:
          type: string
        description: Repository Version referenced by HREF
      - in: query
        name: repository_version_removed
        schema:
          type: string
        description: Repository Version referenced by HREF
      - in: query
        name: tags
        schema:
          type: string
        description: Filter by comma separate list of tags that must all be matched
      - in: query
        name: version
        schema:
          type: string
        description: Filter results where version matches value
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Pulp_Ansible: Default Api V3 Collections Versions'
      deprecated: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCollectionVersionListResponseList'
          description: ''
        '302':
          description: No response body
      summary: Pulp ansible galaxy default api v3 collections versions list
      x-summary-source: derived
  /pulp_ansible/galaxy/default/api/v3/collections/{namespace}/{name}/versions/{version}/:
    get:
      operationId: pulp_ansible_galaxy_default_api_v3_collections_versions_read
      description: Legacy v3 endpoint.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      - in: path
        name: namespace
        schema:
          type: string
        required: true
      - in: path
        name: version
        schema:
          type: string
        required: true
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Pulp_Ansible: Default Api V3 Collections Versions'
      deprecated: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionVersionResponse'
          description: ''
        '302':
          description: No response body
      summary: Pulp ansible galaxy default api v3 collections versions read
      x-summary-source: derived
    delete:
      operationId: pulp_ansible_galaxy_default_api_v3_collections_versions_delete
      description: Legacy v3 endpoint.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      - in: path
        name: namespace
        schema:
          type: string
        required: true
      - in: path
        name: version
        schema:
          type: string
        required: true
      tags:
      - 'Pulp_Ansible: Default Api V3 Collections Versions'
      deprecated: true
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
          description: ''
        '302':
          description: No response body
      summary: Pulp ansible galaxy default api v3 collections versions delete
      x-summary-source: derived
components:
  schemas:
    AsyncOperationResponse:
      type: object
      description: Serializer for asynchronous operations.
      properties:
        task:
          type: string
          format: uri
          description: The href of the task.
      required:
      - task
    CollectionMetadataResponse:
      type: object
      description: A serializer for a CollectionVersion metadata.
      properties:
        authors:
          type: array
          items:
            type: string
            maxLength: 64
          readOnly: true
        contents:
          type: object
          readOnly: true
        dependencies:
          type: object
          readOnly: true
        description:
          type: string
          readOnly: true
        documentation:
          type: string
          readOnly: true
        homepage:
          type: string
          readOnly: true
        issues:
          type: string
          readOnly: true
        license:
          type: array
          items:
            type: string
            maxLength: 32
          readOnly: true
        repository:
          type: string
          readOnly: true
        tags:
          type: array
          items:
            type: string
      required:
      - tags
    CollectionVersionListResponse:
      type: object
      description: A serializer for a CollectionVersion list item.
      properties:
        version:
          type: string
          maxLength: 128
        href:
          type: string
          description: Get href.
          readOnly: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        requires_ansible:
          type:
          - string
          - 'null'
          maxLength: 255
        marks:
          type: array
          items:
            type: string
          description: Get a list of mark values filtering only those in the current repo.
          readOnly: true
      required:
      - created_at
      - updated_at
      - version
    CollectionRefResponse:
      type: object
      description: A serializer for a Collection reference.
      properties:
        id:
          type: string
        name:
          type: string
        href:
          type: string
          description: Returns link to a collection.
          readOnly: true
      required:
      - id
      - name
    CollectionNamespaceResponse:
      type: object
      description: A serializer for a Collection Version namespace field.
      properties:
        name:
          type: string
        metadata_sha256:
          type:
          - string
          - 'null'
      required:
      - metadata_sha256
      - name
    CollectionVersionResponse:
      type: object
      description: A serializer for a CollectionVersion.
      properties:
        version:
          type: string
          maxLength: 128
        href:
          type: string
          description: Get href.
          readOnly: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        requires_ansible:
          type:
          - string
          - 'null'
          maxLength: 255
        marks:
          type: array
          items:
            type: string
          description: Get a list of mark values filtering only those in the current repo.
          readOnly: true
        artifact:
          allOf:
          - $ref: '#/components/schemas/ArtifactRefResponse'
          readOnly: true
        collection:
          allOf:
          - $ref: '#/components/schemas/CollectionRefResponse'
          readOnly: true
        download_url:
          type: string
          description: Get artifact download URL.
          readOnly: true
        name:
          type: string
          readOnly: true
        namespace:
          allOf:
          - $ref: '#/components/schemas/CollectionNamespaceResponse'
          readOnly: true
        signatures:
          type: array
          items:
            $ref: '#/components/schemas/CollectionVersionSignatureResponse'
        metadata:
          allOf:
          - $ref: '#/components/schemas/CollectionMetadataResponse'
          readOnly: true
        git_url:
          type: string
          description: Get the git URL.
          readOnly: true
        git_commit_sha:
          type: string
          description: Get the git commit sha.
          readOnly: true
        manifest:
          type: object
          readOnly: true
          description: A JSON field holding MANIFEST.json data.
        files:
          type: object
          readOnly: true
          description: A JSON field holding FILES.json data.
      required:
      - created_at
      - signatures
      - updated_at
      - version
    PaginatedCollectionVersionListResponseList:
      type: object
      properties:
        meta:
          type: object
          properties:
            count:
              type: integer
              example: 123
        links:
          type: object
          properties:
            first:
              type:
              - string
              - 'null'
            previous:
              type:
              - string
              - 'null'
            next:
              type:
              - string
              - 'null'
            last:
              type:
              - string
              - 'null'
        data:
          type: array
          items:
            $ref: '#/components/schemas/CollectionVersionListResponse'
    ArtifactRefResponse:
      type: object
      description: A serializer for an Artifact reference.
      properties:
        filename:
          type: string
        sha256:
          type: string
        size:
          type: integer
          format: int64
      required:
      - filename
      - sha256
      - size
    CollectionVersionSignatureResponse:
      type: object
      description: A serializer for the signatures on a Collection Version.
      properties:
        signature:
          type: string
          readOnly: true
        pubkey_fingerprint:
          type: string
          maxLength: 64
        signing_service:
          type:
          - string
          - 'null'
          readOnly: true
        pulp_created:
          type: string
          format: date-time
          readOnly: true
      required:
      - pubkey_fingerprint
