openapi: 3.2.0
info:
  title: Automation Hub Repository Versions API
  version: v3
  description: Fetch, Upload, Organize, and Distribute Ansible Collections
  contact:
    name: Automation Hub Team
    email: ansible-galaxy-team@redhat.com
    url: https://www.ansible.com/products/automation-hub
  license:
    name: GPLv2+
    url: https://raw.githubusercontent.com/ansible/galaxy_ng/main/LICENSE
  x-logo:
    url: https://pulp.plan.io/attachments/download/517478/pulp_logo_word_rectangle.svg
  x-pulp-app-versions:
    core: 3.49.40
    galaxy: 4.12.0dev
    ansible: 0.25.1
    container: 2.19.5
    certguard: 3.49.40
    file: 3.49.40
  x-pulp-domain-enabled: false
servers:
- url: http://automation-hub-backend-cwa.automation-hub-prod.svc.cluster.local:8000/
tags:
- name: Repository_Versions
paths:
  /api/automation-hub/pulp/api/v3/repository_versions/:
    get:
      operationId: repository_versions_list
      description: A mixin to hold the shared get_queryset logic used by RepositoryVersionViewSets.
      summary: List repository versions
      parameters:
      - in: query
        name: content
        schema:
          type: string
        description: Content Unit referenced by HREF
      - in: query
        name: content__in
        schema:
          type: string
        description: Content Unit referenced by HREF
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: number
        schema:
          type: integer
        description: Filter results where number matches value
      - in: query
        name: number__gt
        schema:
          type: integer
        description: Filter results where number is greater than value
      - in: query
        name: number__gte
        schema:
          type: integer
        description: Filter results where number is greater than or equal to value
      - in: query
        name: number__lt
        schema:
          type: integer
        description: Filter results where number is less than value
      - in: query
        name: number__lte
        schema:
          type: integer
        description: Filter results where number is less than or equal to value
      - in: query
        name: number__range
        schema:
          type: array
          items:
            type: integer
        description: Filter results where number is between two comma separated values
        explode: false
        style: form
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: ordering
        schema:
          type: array
          items:
            type: string
            enum:
            - -complete
            - -info
            - -number
            - -pk
            - -pulp_created
            - -pulp_id
            - -pulp_last_updated
            - complete
            - info
            - number
            - pk
            - pulp_created
            - pulp_id
            - pulp_last_updated
        description: 'Ordering


          * `pulp_id` - Pulp id

          * `-pulp_id` - Pulp id (descending)

          * `pulp_created` - Pulp created

          * `-pulp_created` - Pulp created (descending)

          * `pulp_last_updated` - Pulp last updated

          * `-pulp_last_updated` - Pulp last updated (descending)

          * `number` - Number

          * `-number` - Number (descending)

          * `complete` - Complete

          * `-complete` - Complete (descending)

          * `info` - Info

          * `-info` - Info (descending)

          * `pk` - Pk

          * `-pk` - Pk (descending)'
        explode: false
        style: form
      - in: query
        name: pulp_created
        schema:
          type: string
          format: date-time
        description: Filter results where pulp_created matches value
      - in: query
        name: pulp_created__gt
        schema:
          type: string
          format: date-time
        description: Filter results where pulp_created is greater than value
      - in: query
        name: pulp_created__gte
        schema:
          type: string
          format: date-time
        description: Filter results where pulp_created is greater than or equal to value
      - in: query
        name: pulp_created__lt
        schema:
          type: string
          format: date-time
        description: Filter results where pulp_created is less than value
      - in: query
        name: pulp_created__lte
        schema:
          type: string
          format: date-time
        description: Filter results where pulp_created is less than or equal to value
      - in: query
        name: pulp_created__range
        schema:
          type: array
          items:
            type: string
            format: date-time
        description: Filter results where pulp_created is between two comma separated values
        explode: false
        style: form
      - in: query
        name: pulp_href__in
        schema:
          type: array
          items:
            type: string
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - in: query
        name: q
        schema:
          type: string
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - Repository_Versions
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedRepositoryVersionResponseList'
          description: ''
components:
  schemas:
    PaginatedRepositoryVersionResponseList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/RepositoryVersionResponse'
    ContentSummaryResponse:
      type: object
      description: Serializer for the RepositoryVersion content summary
      properties:
        added:
          type: object
          additionalProperties:
            type: object
        removed:
          type: object
          additionalProperties:
            type: object
        present:
          type: object
          additionalProperties:
            type: object
      required:
      - added
      - present
      - removed
    RepositoryVersionResponse:
      type: object
      description: 'Base serializer for use with :class:`pulpcore.app.models.Model`


        This ensures that all Serializers provide values for the ''pulp_href` field.


        The class provides a default for the ``ref_name`` attribute in the

        ModelSerializers''s ``Meta`` class. This ensures that the OpenAPI definitions

        of plugins are namespaced properly.'
      properties:
        pulp_href:
          type: string
          format: uri
          readOnly: true
        pulp_created:
          type: string
          format: date-time
          readOnly: true
          description: Timestamp of creation.
        pulp_last_updated:
          type: string
          format: date-time
          readOnly: true
          description: 'Timestamp of the last time this resource was updated. Note: for immutable resources - like content, repository versions, and publication - pulp_created and pulp_last_updated dates will be the same.'
        number:
          type: integer
          format: int64
          readOnly: true
        repository:
          type: string
          format: uri
          readOnly: true
        base_version:
          type: string
          format: uri
          description: A repository version whose content was used as the initial set of content for this repository version
        content_summary:
          allOf:
          - $ref: '#/components/schemas/ContentSummaryResponse'
          readOnly: true
          description: Various count summaries of the content in the version and the HREF to view them.
