openapi: 3.2.0
info:
  title: AWX Ad Hoc Command Events API
  version: v2
  description: AWX API Documentation
  contact:
    email: ansible-community@redhat.com
  license:
    name: Apache License
tags:
- name: ad_hoc_command_events
paths:
  /api/v2/ad_hoc_command_events/{id}/:
    get:
      operationId: ad_hoc_command_events_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          pattern: ^[0-9]+$
        required: true
      tags:
      - ad_hoc_command_events
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdHocCommandEvent'
          description: ''
      summary: Ad hoc command events retrieve
      x-summary-source: derived
components:
  schemas:
    AdHocCommandEvent:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        type:
          type: string
          readOnly: true
        url:
          type: string
          readOnly: true
        related:
          type: string
          readOnly: true
        summary_fields:
          type: string
          readOnly: true
        created:
          type: string
          readOnly: true
        modified:
          type: string
          readOnly: true
        ad_hoc_command:
          type: integer
          readOnly: true
        event:
          enum:
          - runner_on_failed
          - runner_on_ok
          - runner_on_unreachable
          - runner_on_skipped
          - debug
          - verbose
          - deprecated
          - warning
          - system_warning
          - error
          - null
          type:
          - string
          - 'null'
          description: '* `runner_on_failed` - Host Failed

            * `runner_on_ok` - Host OK

            * `runner_on_unreachable` - Host Unreachable

            * `runner_on_skipped` - Host Skipped

            * `debug` - Debug

            * `verbose` - Verbose

            * `deprecated` - Deprecated

            * `warning` - Warning

            * `system_warning` - System Warning

            * `error` - Error'
          x-spec-enum-id: 3c8188cd2c554d8a
        counter:
          type: integer
          minimum: 0
          readOnly: true
        event_display:
          type: string
          readOnly: true
        event_data:
          default: {}
        failed:
          type: boolean
          readOnly: true
        changed:
          type: boolean
          readOnly: true
        uuid:
          type: string
          readOnly: true
        host:
          type:
          - integer
          - 'null'
          readOnly: true
        host_name:
          type: string
          readOnly: true
        stdout:
          type: string
          readOnly: true
        start_line:
          type: integer
          minimum: 0
          readOnly: true
        end_line:
          type: integer
          minimum: 0
          readOnly: true
        verbosity:
          type: integer
          minimum: 0
          readOnly: true
      required:
      - event
