openapi: 3.2.0
info:
  title: 'Automation Hub Api: _Ui V2 Role_Team_Access API'
  version: v3
  description: Fetch, Upload, Organize, and Distribute Ansible Collections
  contact:
    name: Automation Hub Team
    email: ansible-galaxy-team@redhat.com
    url: https://www.ansible.com/products/automation-hub
  license:
    name: GPLv2+
    url: https://raw.githubusercontent.com/ansible/galaxy_ng/main/LICENSE
  x-logo:
    url: https://pulp.plan.io/attachments/download/517478/pulp_logo_word_rectangle.svg
  x-pulp-app-versions:
    core: 3.49.40
    galaxy: 4.12.0dev
    ansible: 0.25.1
    container: 2.19.5
    certguard: 3.49.40
    file: 3.49.40
  x-pulp-domain-enabled: false
servers:
- url: http://automation-hub-backend-cwa.automation-hub-prod.svc.cluster.local:8000/
tags:
- name: 'Api: _Ui V2 Role_Team_Access'
paths:
  /api/automation-hub/_ui/v2/role_team_access/{model_name}/{id}/:
    get:
      operationId: _api_automation-hub__ui_v2_role_team_access_{model_name}_{id}_api_automation_hub__ui_v2_role_team_access_list
      description: 'Use this endpoint to get a list of users who have access to a resource.

        This is a list-only view that provides a list of users, plus extra data.'
      parameters:
      - in: path
        name: id
        schema:
          type: string
          pattern: ^([0-9]+|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$
        required: true
      - in: path
        name: model_name
        schema:
          type: string
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Api: _Ui V2 Role_Team_Access'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTeamAccessViewSet_Team_ResponseList'
          description: ''
      summary: Api automation hub ui v2 role team access {model name} {id} api automation hub…
      x-summary-source: derived
  /api/automation-hub/_ui/v2/role_team_access/{model_name}/{id}/{actor_pk}/:
    get:
      operationId: _api_automation-hub__ui_v2_role_team_access_{model_name}_{id}_{actor_pk}_api_automation_hub__ui_v2_role_team_access_list
      description: 'This gives drill-down information about the means of inheritance

        for all the permissions show in the higher-level view of the access list'
      parameters:
      - in: path
        name: actor_pk
        schema:
          type: string
        required: true
      - in: path
        name: id
        schema:
          type: string
          pattern: ^([0-9]+|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$
        required: true
      - in: path
        name: model_name
        schema:
          type: string
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Api: _Ui V2 Role_Team_Access'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTeamAccessAssignmentResponseList'
          description: ''
      summary: Api automation hub ui v2 role team access {model name} {id} {actor pk} api…
      x-summary-source: derived
components:
  schemas:
    TeamAccessViewSet_Team_Response:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        url:
          type: string
          readOnly: true
        related:
          type: object
          additionalProperties:
            type: string
          readOnly: true
        name:
          type: string
          description: The name of this resource.
          maxLength: 512
        organization:
          type: integer
          format: int64
          description: The organization of this team.
        object_role_assignments:
          type: string
          readOnly: true
      required:
      - name
      - organization
    TeamAccessAssignmentResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        url:
          type: string
          readOnly: true
        related:
          type: object
          additionalProperties:
            type: string
          readOnly: true
        summary_fields:
          type: object
          additionalProperties:
            type: object
          readOnly: true
        created:
          type: string
          format: date-time
          readOnly: true
          description: The date/time this resource was created.
        created_by:
          type:
          - integer
          - 'null'
          format: int64
          readOnly: true
          description: The user who created this resource.
        content_type:
          type: string
          description: String to use for references to this type from other models in the API.
          readOnly: true
        object_id:
          type:
          - string
          - 'null'
          description: The primary key of the object this assignment applies to; null value indicates system-wide assignment.
        object_ansible_id:
          type:
          - string
          - 'null'
          format: uuid
          description: The resource id of the object this role applies to. An alternative to the object_id field.
        role_definition:
          type: integer
          format: int64
          description: The role definition which defines permissions conveyed by this assignment.
        team:
          type: integer
          format: int64
        team_ansible_id:
          type:
          - string
          - 'null'
          format: uuid
          description: The resource ID of the team who will receive permissions from this assignment. An alternative to team field.
      required:
      - role_definition
    PaginatedTeamAccessViewSet_Team_ResponseList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/TeamAccessViewSet_Team_Response'
    PaginatedTeamAccessAssignmentResponseList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/TeamAccessAssignmentResponse'
