openapi: 3.2.0
info:
  title: 'Automation Hub Api: _Ui V1 Imports Collections API'
  version: v3
  description: Fetch, Upload, Organize, and Distribute Ansible Collections
  contact:
    name: Automation Hub Team
    email: ansible-galaxy-team@redhat.com
    url: https://www.ansible.com/products/automation-hub
  license:
    name: GPLv2+
    url: https://raw.githubusercontent.com/ansible/galaxy_ng/main/LICENSE
  x-logo:
    url: https://pulp.plan.io/attachments/download/517478/pulp_logo_word_rectangle.svg
  x-pulp-app-versions:
    core: 3.49.40
    galaxy: 4.12.0dev
    ansible: 0.25.1
    container: 2.19.5
    certguard: 3.49.40
    file: 3.49.40
  x-pulp-domain-enabled: false
servers:
- url: http://automation-hub-backend-cwa.automation-hub-prod.svc.cluster.local:8000/
tags:
- name: 'Api: _Ui V1 Imports Collections'
paths:
  /api/automation-hub/_ui/v1/imports/collections/:
    get:
      operationId: api_automation_hub__ui_v1_imports_collections_list
      description: ViewSet for CollectionImports.
      summary: List collection imports
      parameters:
      - in: query
        name: created
        schema:
          type: string
          format: date
      - in: query
        name: keywords
        schema:
          type: string
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: name
        schema:
          type: string
      - in: query
        name: namespace
        schema:
          type: string
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: sort
        schema:
          type: array
          items:
            type: string
            enum:
            - -created
            - created
        description: 'Ordering


          * `created` - Created

          * `-created` - Created (descending)'
        explode: false
        style: form
      - in: query
        name: state
        schema:
          type: string
      - in: query
        name: version
        schema:
          type: string
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Api: _Ui V1 Imports Collections'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedImportTaskListResponseList'
          description: ''
  /api/automation-hub/_ui/v1/imports/collections/{task_id}/:
    get:
      operationId: api_automation_hub__ui_v1_imports_collections_read
      description: Returns a CollectionImport object.
      summary: Retrieve collection import
      parameters:
      - in: path
        name: task_id
        schema:
          type: string
          format: uuid
        description: A unique value identifying this collection import.
        required: true
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Api: _Ui V1 Imports Collections'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportTaskDetailResponse'
          description: ''
components:
  schemas:
    ImportTaskListResponse:
      type: object
      description: A serializer for a CollectionImport list view.
      properties:
        id:
          type: string
          format: uuid
        state:
          type: string
        namespace:
          type: string
        name:
          type: string
        version:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        started_at:
          type: string
          format: date-time
        finished_at:
          type: string
          format: date-time
      required:
      - created_at
      - finished_at
      - id
      - name
      - namespace
      - started_at
      - state
      - updated_at
      - version
    PaginatedImportTaskListResponseList:
      type: object
      properties:
        meta:
          type: object
          properties:
            count:
              type: integer
              example: 123
        links:
          type: object
          properties:
            first:
              type:
              - string
              - 'null'
            previous:
              type:
              - string
              - 'null'
            next:
              type:
              - string
              - 'null'
            last:
              type:
              - string
              - 'null'
        data:
          type: array
          items:
            $ref: '#/components/schemas/ImportTaskListResponse'
    ImportTaskDetailResponse:
      type: object
      description: A serializer for a CollectionImport list view.
      properties:
        id:
          type: string
          format: uuid
        state:
          type: string
        namespace:
          type: string
        name:
          type: string
        version:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        started_at:
          type: string
          format: date-time
        finished_at:
          type: string
          format: date-time
        error:
          type: object
        messages:
          type: object
      required:
      - created_at
      - error
      - finished_at
      - id
      - messages
      - name
      - namespace
      - started_at
      - state
      - updated_at
      - version
