openapi: 3.2.0
info:
  title: 'Automation Hub Api: V3 Auth Token API'
  version: v3
  description: Fetch, Upload, Organize, and Distribute Ansible Collections
  contact:
    name: Automation Hub Team
    email: ansible-galaxy-team@redhat.com
    url: https://www.ansible.com/products/automation-hub
  license:
    name: GPLv2+
    url: https://raw.githubusercontent.com/ansible/galaxy_ng/main/LICENSE
  x-logo:
    url: https://pulp.plan.io/attachments/download/517478/pulp_logo_word_rectangle.svg
  x-pulp-app-versions:
    core: 3.49.40
    galaxy: 4.12.0dev
    ansible: 0.25.1
    container: 2.19.5
    certguard: 3.49.40
    file: 3.49.40
  x-pulp-domain-enabled: false
servers:
- url: http://automation-hub-backend-cwa.automation-hub-prod.svc.cluster.local:8000/
tags:
- name: 'Api: V3 Auth Token'
paths:
  /api/automation-hub/v3/auth/token/:
    post:
      operationId: api_automation_hub_v3_auth_token_post
      description: Create or refresh user token.
      tags:
      - 'Api: V3 Auth Token'
      responses:
        '200':
          description: No response body
      summary: Api automation hub v3 auth token post
      x-summary-source: derived
    delete:
      operationId: api_automation_hub_v3_auth_token_delete
      description: Invalidate user token.
      tags:
      - 'Api: V3 Auth Token'
      responses:
        '204':
          description: No response body
      summary: Api automation hub v3 auth token delete
      x-summary-source: derived
