openapi: 3.2.0
info:
  title: 'Automation Hub Contentguards: X509 API'
  version: v3
  description: Fetch, Upload, Organize, and Distribute Ansible Collections
  contact:
    name: Automation Hub Team
    email: ansible-galaxy-team@redhat.com
    url: https://www.ansible.com/products/automation-hub
  license:
    name: GPLv2+
    url: https://raw.githubusercontent.com/ansible/galaxy_ng/main/LICENSE
  x-logo:
    url: https://pulp.plan.io/attachments/download/517478/pulp_logo_word_rectangle.svg
  x-pulp-app-versions:
    core: 3.49.40
    galaxy: 4.12.0dev
    ansible: 0.25.1
    container: 2.19.5
    certguard: 3.49.40
    file: 3.49.40
  x-pulp-domain-enabled: false
servers:
- url: http://automation-hub-backend-cwa.automation-hub-prod.svc.cluster.local:8000/
tags:
- name: 'Contentguards: X509'
paths:
  /api/automation-hub/pulp/api/v3/contentguards/certguard/x509/:
    get:
      operationId: contentguards_certguard_x509_list
      description: X509CertGuard API Viewsets.
      summary: List x509 cert guards
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: name
        schema:
          type: string
        description: Filter results where name matches value
      - in: query
        name: name__contains
        schema:
          type: string
        description: Filter results where name contains value
      - in: query
        name: name__icontains
        schema:
          type: string
        description: Filter results where name contains value
      - in: query
        name: name__iexact
        schema:
          type: string
        description: Filter results where name matches value
      - in: query
        name: name__in
        schema:
          type: array
          items:
            type: string
        description: Filter results where name is in a comma-separated list of values
        explode: false
        style: form
      - in: query
        name: name__iregex
        schema:
          type: string
        description: Filter results where name matches regex value
      - in: query
        name: name__istartswith
        schema:
          type: string
        description: Filter results where name starts with value
      - in: query
        name: name__regex
        schema:
          type: string
        description: Filter results where name matches regex value
      - in: query
        name: name__startswith
        schema:
          type: string
        description: Filter results where name starts with value
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: ordering
        schema:
          type: array
          items:
            type: string
            enum:
            - -description
            - -name
            - -pk
            - -pulp_created
            - -pulp_id
            - -pulp_last_updated
            - -pulp_type
            - description
            - name
            - pk
            - pulp_created
            - pulp_id
            - pulp_last_updated
            - pulp_type
        description: 'Ordering


          * `pulp_id` - Pulp id

          * `-pulp_id` - Pulp id (descending)

          * `pulp_created` - Pulp created

          * `-pulp_created` - Pulp created (descending)

          * `pulp_last_updated` - Pulp last updated

          * `-pulp_last_updated` - Pulp last updated (descending)

          * `pulp_type` - Pulp type

          * `-pulp_type` - Pulp type (descending)

          * `name` - Name

          * `-name` - Name (descending)

          * `description` - Description

          * `-description` - Description (descending)

          * `pk` - Pk

          * `-pk` - Pk (descending)'
        explode: false
        style: form
      - in: query
        name: pulp_href__in
        schema:
          type: array
          items:
            type: string
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - in: query
        name: pulp_id__in
        schema:
          type: array
          items:
            type: string
            format: uuid
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - in: query
        name: q
        schema:
          type: string
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Contentguards: X509'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Paginatedcertguard.X509CertGuardResponseList'
          description: ''
    post:
      operationId: contentguards_certguard_x509_create
      description: X509CertGuard API Viewsets.
      summary: Create a x509 cert guard
      tags:
      - 'Contentguards: X509'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/certguard.X509CertGuard'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/certguard.X509CertGuard'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/certguard.X509CertGuard'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/certguard.X509CertGuardResponse'
          description: ''
  /api/automation-hub/pulp/api/v3/contentguards/certguard/x509/{pulp_id}/:
    get:
      operationId: contentguards_certguard_x509_read
      description: X509CertGuard API Viewsets.
      summary: Inspect a x509 cert guard
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this x509 cert guard.
        required: true
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - 'Contentguards: X509'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/certguard.X509CertGuardResponse'
          description: ''
    put:
      operationId: contentguards_certguard_x509_update
      description: X509CertGuard API Viewsets.
      summary: Update a x509 cert guard
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this x509 cert guard.
        required: true
      tags:
      - 'Contentguards: X509'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/certguard.X509CertGuard'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/certguard.X509CertGuard'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/certguard.X509CertGuard'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/certguard.X509CertGuardResponse'
          description: ''
    patch:
      operationId: contentguards_certguard_x509_partial_update
      description: X509CertGuard API Viewsets.
      summary: Update a x509 cert guard
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this x509 cert guard.
        required: true
      tags:
      - 'Contentguards: X509'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patchedcertguard.X509CertGuard'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Patchedcertguard.X509CertGuard'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Patchedcertguard.X509CertGuard'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/certguard.X509CertGuardResponse'
          description: ''
    delete:
      operationId: contentguards_certguard_x509_delete
      description: X509CertGuard API Viewsets.
      summary: Delete a x509 cert guard
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this x509 cert guard.
        required: true
      tags:
      - 'Contentguards: X509'
      responses:
        '204':
          description: No response body
components:
  schemas:
    certguard.X509CertGuard:
      type: object
      description: X.509 Content Guard Serializer.
      properties:
        name:
          type: string
          minLength: 1
          description: The unique name.
        description:
          type:
          - string
          - 'null'
          minLength: 1
          description: An optional description.
        ca_certificate:
          type: string
          minLength: 1
          description: A Certificate Authority (CA) certificate (or a bundle thereof) used to verify client-certificate authenticity.
      required:
      - ca_certificate
      - name
    certguard.X509CertGuardResponse:
      type: object
      description: X.509 Content Guard Serializer.
      properties:
        pulp_href:
          type: string
          format: uri
          readOnly: true
        pulp_created:
          type: string
          format: date-time
          readOnly: true
          description: Timestamp of creation.
        pulp_last_updated:
          type: string
          format: date-time
          readOnly: true
          description: 'Timestamp of the last time this resource was updated. Note: for immutable resources - like content, repository versions, and publication - pulp_created and pulp_last_updated dates will be the same.'
        name:
          type: string
          description: The unique name.
        description:
          type:
          - string
          - 'null'
          description: An optional description.
        ca_certificate:
          type: string
          description: A Certificate Authority (CA) certificate (or a bundle thereof) used to verify client-certificate authenticity.
      required:
      - ca_certificate
      - name
    Paginatedcertguard.X509CertGuardResponseList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/certguard.X509CertGuardResponse'
    Patchedcertguard.X509CertGuard:
      type: object
      description: X.509 Content Guard Serializer.
      properties:
        name:
          type: string
          minLength: 1
          description: The unique name.
        description:
          type:
          - string
          - 'null'
          minLength: 1
          description: An optional description.
        ca_certificate:
          type: string
          minLength: 1
          description: A Certificate Authority (CA) certificate (or a bundle thereof) used to verify client-certificate authenticity.
