openapi: 3.2.0
info:
  title: 'Automation Hub Users: Roles API'
  version: v3
  description: Fetch, Upload, Organize, and Distribute Ansible Collections
  contact:
    name: Automation Hub Team
    email: ansible-galaxy-team@redhat.com
    url: https://www.ansible.com/products/automation-hub
  license:
    name: GPLv2+
    url: https://raw.githubusercontent.com/ansible/galaxy_ng/main/LICENSE
  x-logo:
    url: https://pulp.plan.io/attachments/download/517478/pulp_logo_word_rectangle.svg
  x-pulp-app-versions:
    core: 3.49.40
    galaxy: 4.12.0dev
    ansible: 0.25.1
    container: 2.19.5
    certguard: 3.49.40
    file: 3.49.40
  x-pulp-domain-enabled: false
servers:
- url: http://automation-hub-backend-cwa.automation-hub-prod.svc.cluster.local:8000/
tags:
- name: Users - Roles
paths:
  /api/automation-hub/pulp/api/v3/users/{user_pk}/roles/:
    get:
      operationId: users_roles_list
      description: ViewSet for UserRole.
      summary: List user roles
      parameters:
      - in: query
        name: content_object
        schema:
          type: string
        description: content_object
      - in: query
        name: domain
        schema:
          type: string
          format: uuid
        description: Foreign Key referenced by HREF
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: ordering
        schema:
          type: array
          items:
            type: string
            enum:
            - -description
            - -pk
            - -pulp_created
            - -role
            - description
            - pk
            - pulp_created
            - role
        description: 'Ordering


          * `role` - Role

          * `-role` - Role (descending)

          * `description` - Description

          * `-description` - Description (descending)

          * `pulp_created` - Pulp created

          * `-pulp_created` - Pulp created (descending)

          * `pk` - Pk

          * `-pk` - Pk (descending)'
        explode: false
        style: form
      - in: query
        name: pulp_href__in
        schema:
          type: array
          items:
            type: string
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - in: query
        name: pulp_id__in
        schema:
          type: array
          items:
            type: string
            format: uuid
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - in: query
        name: q
        schema:
          type: string
      - in: query
        name: role
        schema:
          type: string
      - in: query
        name: role__contains
        schema:
          type: string
      - in: query
        name: role__icontains
        schema:
          type: string
      - in: query
        name: role__in
        schema:
          type: array
          items:
            type: string
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - in: query
        name: role__startswith
        schema:
          type: string
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - Users - Roles
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserRoleResponseList'
          description: ''
    post:
      operationId: users_roles_create
      description: ViewSet for UserRole.
      summary: Create an user role
      parameters:
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      tags:
      - Users - Roles
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRole'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRole'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserRole'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRoleResponse'
          description: ''
  /api/automation-hub/pulp/api/v3/users/{user_pk}/roles/{pulp_id}/:
    get:
      operationId: users_roles_read
      description: ViewSet for UserRole.
      summary: Inspect an user role
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this user role.
        required: true
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      - in: query
        name: fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to include in the response.
      - in: query
        name: exclude_fields
        schema:
          type: array
          items:
            type: string
        description: A list of fields to exclude from the response.
      tags:
      - Users - Roles
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRoleResponse'
          description: ''
    delete:
      operationId: users_roles_delete
      description: ViewSet for UserRole.
      summary: Delete an user role
      parameters:
      - in: path
        name: pulp_id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this user role.
        required: true
      - in: path
        name: user_pk
        schema:
          type: string
        required: true
      tags:
      - Users - Roles
      responses:
        '204':
          description: No response body
components:
  schemas:
    PaginatedUserRoleResponseList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/UserRoleResponse'
    UserRoleResponse:
      type: object
      description: Serializer for UserRole.
      properties:
        pulp_href:
          type: string
          format: uri
          readOnly: true
        pulp_created:
          type: string
          format: date-time
          readOnly: true
          description: Timestamp of creation.
        pulp_last_updated:
          type: string
          format: date-time
          readOnly: true
          description: 'Timestamp of the last time this resource was updated. Note: for immutable resources - like content, repository versions, and publication - pulp_created and pulp_last_updated dates will be the same.'
        role:
          type: string
        content_object:
          type:
          - string
          - 'null'
          description: pulp_href of the object for which role permissions should be asserted. If set to 'null', permissions will act on either domain or model-level.
        description:
          type: string
          readOnly: true
        permissions:
          type: array
          items:
            type: string
          readOnly: true
        domain:
          type:
          - string
          - 'null'
          format: uri
          description: Domain this role should be applied on, mutually exclusive with content_object.
      required:
      - content_object
      - role
    UserRole:
      type: object
      description: Serializer for UserRole.
      properties:
        role:
          type: string
          minLength: 1
        content_object:
          type:
          - string
          - 'null'
          minLength: 1
          description: pulp_href of the object for which role permissions should be asserted. If set to 'null', permissions will act on either domain or model-level.
        domain:
          type:
          - string
          - 'null'
          format: uri
          description: Domain this role should be applied on, mutually exclusive with content_object.
      required:
      - content_object
      - role
